openapi: 3.1.1
info:
  title: API do Sistema de Casa de Ração
  description: API para gerenciamento de casa de ração - clientes, estoque e usuários
  version: 1.0.0

tags:
  - Clientes
  - Estoques
  - Usuarios

paths:
  /api/clientes:
    $ref: './paths/Cliente/Collection.yaml'
  /api/clientes/{id}:
    $ref: './paths/Cliente/Item.yaml'
  /api/estoques:
    $ref: './paths/Estoque/Collection.yaml'
  /api/estoques/{id}:
    $ref: './paths/Estoque/Item.yaml'
  /api/usuarios:
    $ref: './paths/Usuario/Collection.yaml'
  /api/usuarios/{id}:
    $ref: './paths/Usuario/Item.yaml'

components:
  schemas:
    Cliente:
      $ref: './components/Cliente.yaml'
    Estoque:
      $ref: './components/Estoque.yaml'
    Usuario:
      $ref: './components/Usuario.yaml'